lab1 finished
Egoroff85/direngine-django-sample pull request #1
Opened 2020-03-08 20:23 UTC by Egoroff85

Лабораторная работа № 1.

2020-03-10 09:41 UTC, EnotYoyo reviewed
Поправить только post-вьюшки, остальное отлично.

2020-03-10 09:41 UTC, EnotYoyo commented on direngine/pages/views.py
> +        html = '<html><body>'
Получается, что тут формирование html - страницы. Для формирования html - страниц используются темплейты. Перепишите это с использованием темплейтов (в темплейты можно передавать параметры из питон-кода) :)

2020-03-10 21:07 UTC, Egoroff85 commented on direngine/pages/views.py
> +        html = '<html><body>'
Добавлены шаблоны для обработки POST-запросов пользователя

2020-03-10 21:20 UTC, EnotYoyo requested changes

2020-03-10 21:20 UTC, EnotYoyo commented on direngine/pages/templates/hotel-search.html
> +{% include 'partials/_head.html' %}
Да, Вы пришли к правильному выводу, что у темплейтов есть общие куски кода, которые логично выносить в отдельные файлы. Для этого используют [механику наследования шаблонов](https://docs.djangoproject.com/en/3.0/ref/templates/language/#template-inheritance).

2020-03-11 20:30 UTC, Egoroff85 commented on direngine/pages/templates/hotel-search.html
> +{% include 'partials/_head.html' %}
Действительно, удобный инструмент! Переделал с использованием наследования шаблонов.

2020-03-12 10:45 UTC, EnotYoyo approved these changes

2020-03-12 11:08 UTC, merged